---
title: "Promo_atr_datacleam"
author: "Yantao Liu"
date: "January 29, 2018"
output: html_document
---
Setup env 
```{r}
rm(list = ls())
gc()
library(data.table)

```
Import data 

```{r}

# promo.atr = fread("DDFSPT_ALGORITHM_INPUT_VARS.txt", header = TRUE, stringsAsFactors = T,
#                   na.strings = c("N/A", ""),
#                   colClasses = list(factor = c("FLYER_SLOT_PRIORITY_CD", "CATEGORY_CD", "SUBCATEGORY_CD", "FINELINE_CD"),
#                                       Date = c("WKSALE_START_DATE")),
#                   drop = c("PACKAGE_VOLUME_QTY","FORECAST_STORE_ORDER_QTY","FORECAST_FINAL_POS_FCTORED_QTY",  
#                            "UNFACTORED_POS_FCST_QTY", "DMOQ_QTY", "OGBB", "PRODUCT_PROFILE", "EAP_IND" ))
promo.atr = fread("PROMO_ATR.txt", header = T, stringsAsFactors = T, na.strings = c("N/A", ""),
                  colClasses = list(factor = c("DEAL_YEAR", "DEAL_NUM", "DEAL_START_WEEK_NUM")))
c445.cal = fread("calendar.txt", header = T,
                 colClasses = list(factor = c("C445_WK_NUM", "C445_YR_NUM"),
                                   Date   = c("C445_WK_STRT_DATE"))) 

base.data = fread("model_data_sku_LOB_GF.txt", header = TRUE, stringsAsFactors = TRUE, colClasses = list(factor = "CATEGORY_CD"))

```
